server:
  port: 8085
spring:
  application:
    name: spring-security-learning
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/company?useSSL=true
    username: root
    password: Sammy@2895
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create
  #    properties:
  #      hibernate:
  #        format_sql: true
  main:
    banner-mode: off
#   Default user to be created for spring security dependency
#  security:
#    user:
#      name: root
#      password: Sammy@2895